CREATE TABLE MEDICINE(
MEDICINEID INT PRIMARY KEY AUTO_INCREMENT,
MEDICINENAME VARCHAR(255),
MEDICINECOMPANY VARCHAR(255),
MEDICINEPRICE INT,
QUANTITY INT,
EXPIREDATE VARCHAR(15)
);
CREATE TABLE DOCTOR(
DOCTORID INT PRIMARY KEY AUTO_INCREMENT,
DOCTORNAME VARCHAR(255),
DOCTORSPECIALITY VARCHAR(255),
DOCTORCHARGE INT,
DOCTORVISITINGDAY VARCHAR(50),
DOCTORCONTACT VARCHAR(15)
);
CREATE TABLE PATIENT(
PATIENTID INT PRIMARY KEY AUTO_INCREMENT,
PATIENTNAME VARCHAR(100),
P_GENDER VARCHAR(10),
PATIENTAGE INT,
APPOINTMENTDATE VARCHAR(50),
P_PROBLEM VARCHAR(100),
P_MEDICINE VARCHAR(100)
);